package net.yeoxuhang.geode_plus.server.registry;

import net.minecraft.core.registries.Registries;
import net.minecraft.data.worldgen.BootstrapContext;
import net.minecraft.resources.ResourceKey;
import net.minecraft.util.valueproviders.UniformInt;
import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.level.levelgen.GeodeBlockSettings;
import net.minecraft.world.level.levelgen.GeodeCrackSettings;
import net.minecraft.world.level.levelgen.GeodeLayerSettings;
import net.minecraft.world.level.levelgen.feature.ConfiguredFeature;
import net.minecraft.world.level.levelgen.feature.Feature;
import net.minecraft.world.level.levelgen.feature.configurations.FeatureConfiguration;
import net.minecraft.world.level.levelgen.feature.configurations.GeodeConfiguration;
import net.minecraft.world.level.levelgen.feature.stateproviders.BlockStateProvider;
import net.minecraft.world.level.levelgen.placement.CaveSurface;
import net.yeoxuhang.geode_plus.server.world.feature.config.GeodeCrystalSpikeConfig;

import java.util.List;

import static net.minecraft.world.level.levelgen.feature.stateproviders.BlockStateProvider.simple;
import static net.yeoxuhang.geode_plus.server.registry.BlockRegistry.*;

public class ConfiguredFeatureRegistry {
    public static final ResourceKey<ConfiguredFeature<?, ?>> PRISMARINE_GEODE = registerKey("prismarine_geode");
    public static final ResourceKey<ConfiguredFeature<?, ?>> WRAPPIST_GEODE = registerKey("wrappist_geode");
    public static final ResourceKey<ConfiguredFeature<?, ?>> ECHO_GEODE = registerKey("echo_geode");
    public static final ResourceKey<ConfiguredFeature<?, ?>> NETHER_QUARTZ_CRYSTAL_SPIKE = registerKey(
            "nether_quartz_crystal_spike");
    public static final ResourceKey<ConfiguredFeature<?, ?>> NETHER_QUARTZ_CRYSTAL_SPIKE_FLOOR = registerKey(
            "nether_quartz_crystal_spike_floor");
    public static final ResourceKey<ConfiguredFeature<?, ?>> GLOWSTONE_CRYSTAL_SPIKE = registerKey(
            "glowstone_crystal_spike");
    public static final ResourceKey<ConfiguredFeature<?, ?>> GLOWSTONE_CRYSTAL_SPIKE_FLOOR = registerKey(
            "glowstone_crystal_spike_floor");
    public static final ResourceKey<ConfiguredFeature<?, ?>> ECHO_CRYSTAL_SPIKE = registerKey("echo_crystal_spike");
    public static final ResourceKey<ConfiguredFeature<?, ?>> ECHO_CRYSTAL_SPIKE_FLOOR = registerKey(
            "echo_crystal_spike_floor");
    public static final ResourceKey<ConfiguredFeature<?, ?>> PRISMARINE_CRYSTAL_SPIKE = registerKey(
            "prismarine_crystal_spike");
    public static final ResourceKey<ConfiguredFeature<?, ?>> WRAPPIST_CRYSTAL_SPIKE = registerKey(
            "wrappist_crystal_spike");
    public static final ResourceKey<ConfiguredFeature<?, ?>> ANCIENT_DEBRIS_GEODE = registerKey("ancient_debris_geode");
    public static final ResourceKey<ConfiguredFeature<?, ?>> BASALT_ANCIENT_DEBRIS_GEODE = registerKey(
            "basalt_ancient_debris_geode");
    public static final ResourceKey<ConfiguredFeature<?, ?>> BLACKSTONE_ANCIENT_DEBRIS_GEODE = registerKey(
            "blackstone_ancient_debris_geode");
    public static final ResourceKey<ConfiguredFeature<?, ?>> GLOWSTONE_GEODE = registerKey("glowstone_geode");
    public static final ResourceKey<ConfiguredFeature<?, ?>> BASALT_GLOWSTONE_GEODE = registerKey(
            "basalt_glowstone_geode");
    public static final ResourceKey<ConfiguredFeature<?, ?>> BLACKSTONE_GLOWSTONE_GEODE = registerKey(
            "blackstone_glowstone_geode");
    public static final ResourceKey<ConfiguredFeature<?, ?>> GOLD_NUGGET_GEODE = registerKey("gold_nugget_geode");
    public static final ResourceKey<ConfiguredFeature<?, ?>> BASALT_GOLD_NUGGET_GEODE = registerKey(
            "basalt_gold_nugget_geode");
    public static final ResourceKey<ConfiguredFeature<?, ?>> BLACKSTONE_GOLD_NUGGET_GEODE = registerKey(
            "blackstone_gold_nugget_geode");

    public static final ResourceKey<ConfiguredFeature<?, ?>> QUARTZ_GEODE = registerKey("quartz_geode");
    public static final ResourceKey<ConfiguredFeature<?, ?>> BASALT_QUARTZ_GEODE = registerKey("basalt_quartz_geode");
    public static final ResourceKey<ConfiguredFeature<?, ?>> BLACKSTONE_QUARTZ_GEODE = registerKey(
            "blackstone_quartz_geode");

    public static final ResourceKey<ConfiguredFeature<?, ?>> DIAMOND_GEODE = registerKey("diamond_geode");
    public static final ResourceKey<ConfiguredFeature<?, ?>> DEEPSLATE_DIAMOND_GEODE = registerKey(
            "deepslate_diamond_geode");
    public static final ResourceKey<ConfiguredFeature<?, ?>> SCULK_DIAMOND_GEODE = registerKey("sculk_diamond_geode");

    public static final ResourceKey<ConfiguredFeature<?, ?>> EMERALD_GEODE = registerKey("emerald_geode");
    public static final ResourceKey<ConfiguredFeature<?, ?>> DEEPSLATE_EMERALD_GEODE = registerKey(
            "deepslate_emerald_geode");
    public static final ResourceKey<ConfiguredFeature<?, ?>> SCULK_EMERALD_GEODE = registerKey("sculk_emerald_geode");

    public static final ResourceKey<ConfiguredFeature<?, ?>> LAPIS_GEODE = registerKey("lapis_geode");
    public static final ResourceKey<ConfiguredFeature<?, ?>> DEEPSLATE_LAPIS_GEODE = registerKey("deepslate_lapis_geode");
    public static final ResourceKey<ConfiguredFeature<?, ?>> SCULK_LAPIS_GEODE = registerKey("sculk_lapis_geode");

    public static final ResourceKey<ConfiguredFeature<?, ?>> REDSTONE_GEODE = registerKey("redstone_geode");
    public static final ResourceKey<ConfiguredFeature<?, ?>> DEEPSLATE_REDSTONE_GEODE = registerKey(
            "deepslate_redstone_geode");
    public static final ResourceKey<ConfiguredFeature<?, ?>> SCULK_REDSTONE_GEODE = registerKey("sculk_redstone_geode");

    public static final ResourceKey<ConfiguredFeature<?, ?>> CELESTITE_GEODE = registerKey("celestite_geode");
    public static final ResourceKey<ConfiguredFeature<?, ?>> PINK_TOPAZ_GEODE = registerKey("pink_topaz_geode");

    public static void bootstrap(BootstrapContext<ConfiguredFeature<?, ?>> context) {
        register(context,
                NETHER_QUARTZ_CRYSTAL_SPIKE,
                FeatureRegistry.NETHER_CRYSTAL_SPIKE.value(),
                new GeodeCrystalSpikeConfig(BlockStateProvider.simple(NETHER_QUARTZ_CRYSTAL_BLOCK.value()),
                        BlockStateProvider.simple(NETHER_QUARTZ_CRYSTAL.value()),
                        UniformInt.of(1, 3),
                        CaveSurface.CEILING));
        register(context,
                NETHER_QUARTZ_CRYSTAL_SPIKE_FLOOR,
                FeatureRegistry.NETHER_CRYSTAL_SPIKE.value(),
                new GeodeCrystalSpikeConfig(BlockStateProvider.simple(NETHER_QUARTZ_CRYSTAL_BLOCK.value()),
                        BlockStateProvider.simple(NETHER_QUARTZ_CRYSTAL.value()),
                        UniformInt.of(1, 3),
                        CaveSurface.FLOOR));
        register(context,
                GLOWSTONE_CRYSTAL_SPIKE,
                FeatureRegistry.NETHER_CRYSTAL_SPIKE.value(),
                new GeodeCrystalSpikeConfig(BlockStateProvider.simple(GLOWSTONE_CLUSTER_BLOCK.value()),
                        BlockStateProvider.simple(GLOWSTONE_CLUSTER.value()),
                        UniformInt.of(1, 3),
                        CaveSurface.CEILING));
        register(context,
                GLOWSTONE_CRYSTAL_SPIKE_FLOOR,
                FeatureRegistry.NETHER_CRYSTAL_SPIKE.value(),
                new GeodeCrystalSpikeConfig(BlockStateProvider.simple(GLOWSTONE_CLUSTER_BLOCK.value()),
                        BlockStateProvider.simple(GLOWSTONE_CLUSTER.value()),
                        UniformInt.of(1, 3),
                        CaveSurface.FLOOR));
        register(context,
                ECHO_CRYSTAL_SPIKE,
                FeatureRegistry.ECHO_CRYSTAL_SPIKE.value(),
                new GeodeCrystalSpikeConfig(BlockStateProvider.simple(Blocks.SCULK),
                        BlockStateProvider.simple(ECHO_CRYSTAL.value()),
                        UniformInt.of(1, 3),
                        CaveSurface.CEILING));
        register(context,
                ECHO_CRYSTAL_SPIKE_FLOOR,
                FeatureRegistry.ECHO_CRYSTAL_SPIKE.value(),
                new GeodeCrystalSpikeConfig(BlockStateProvider.simple(Blocks.SCULK),
                        BlockStateProvider.simple(ECHO_CRYSTAL.value()),
                        UniformInt.of(1, 3),
                        CaveSurface.FLOOR));
        register(context,
                WRAPPIST_CRYSTAL_SPIKE,
                FeatureRegistry.WRAPPIST_CRYSTAL_SPIKE.value(),
                new GeodeCrystalSpikeConfig(BlockStateProvider.simple(WRAPPIST_BLOCK.value()),
                        BlockStateProvider.simple(WRAPPIST_CLUSTER.value()),
                        UniformInt.of(1, 3),
                        CaveSurface.FLOOR));
        register(context,
                PRISMARINE_CRYSTAL_SPIKE,
                FeatureRegistry.OCEAN_CRYSTAL_SPIKE.value(),
                new GeodeCrystalSpikeConfig(BlockStateProvider.simple(PRISMARINE_CLUSTER_BLOCK.value()),
                        BlockStateProvider.simple(PRISMARINE_CLUSTER.value()),
                        UniformInt.of(1, 3),
                        CaveSurface.FLOOR));
        register(context,
                ANCIENT_DEBRIS_GEODE,
                FeatureRegistry.GEODE.value(),
                new GeodeConfiguration(new GeodeBlockSettings(simple(Blocks.AIR),
                        simple(Blocks.NETHERRACK),
                        simple(BUDDING_ANCIENT_DEBRIS.value()),
                        simple(Blocks.NETHERRACK),
                        simple(Blocks.NETHERRACK),
                        List.of(SMALL_ANCIENT_DEBRIS_BUD.value().defaultBlockState(),
                                MEDIUM_ANCIENT_DEBRIS_BUD.value().defaultBlockState(),
                                LARGE_ANCIENT_DEBRIS_BUD.value().defaultBlockState(),
                                ANCIENT_DEBRIS_CLUSTER.value().defaultBlockState()),
                        TagRegistry.Blocks.GEODES_CANNOT_REPLACE,
                        TagRegistry.Blocks.GEODE_INVALID_BLOCKS),
                        new GeodeLayerSettings(1.7D, 2.2D, 3.2D, 4.2D),
                        new GeodeCrackSettings(0.95D, 2.0D, 2),
                        0.35D,
                        0.083D,
                        true,
                        UniformInt.of(4, 6),
                        UniformInt.of(3, 4),
                        UniformInt.of(1, 2),
                        -16,
                        16,
                        0.05D,
                        1));
        register(context,
                BASALT_ANCIENT_DEBRIS_GEODE,
                FeatureRegistry.GEODE.value(),
                new GeodeConfiguration(new GeodeBlockSettings(simple(Blocks.AIR),
                        simple(Blocks.NETHERRACK),
                        simple(BUDDING_BASALT_ANCIENT_DEBRIS.value()),
                        simple(Blocks.NETHERRACK),
                        simple(Blocks.NETHERRACK),
                        List.of(SMALL_ANCIENT_DEBRIS_BUD.value().defaultBlockState(),
                                MEDIUM_ANCIENT_DEBRIS_BUD.value().defaultBlockState(),
                                LARGE_ANCIENT_DEBRIS_BUD.value().defaultBlockState(),
                                ANCIENT_DEBRIS_CLUSTER.value().defaultBlockState()),
                        TagRegistry.Blocks.GEODES_CANNOT_REPLACE,
                        TagRegistry.Blocks.GEODE_INVALID_BLOCKS),
                        new GeodeLayerSettings(1.7D, 2.2D, 3.2D, 4.2D),
                        new GeodeCrackSettings(0.95D, 2.0D, 2),
                        0.35D,
                        0.083D,
                        true,
                        UniformInt.of(4, 6),
                        UniformInt.of(3, 4),
                        UniformInt.of(1, 2),
                        -16,
                        16,
                        0.05D,
                        1));
        register(context,
                BLACKSTONE_ANCIENT_DEBRIS_GEODE,
                FeatureRegistry.GEODE.value(),
                new GeodeConfiguration(new GeodeBlockSettings(simple(Blocks.AIR),
                        simple(Blocks.NETHERRACK),
                        simple(BUDDING_BLACKSTONE_ANCIENT_DEBRIS.value()),
                        simple(Blocks.NETHERRACK),
                        simple(Blocks.NETHERRACK),
                        List.of(SMALL_ANCIENT_DEBRIS_BUD.value().defaultBlockState(),
                                MEDIUM_ANCIENT_DEBRIS_BUD.value().defaultBlockState(),
                                LARGE_ANCIENT_DEBRIS_BUD.value().defaultBlockState(),
                                ANCIENT_DEBRIS_CLUSTER.value().defaultBlockState()),
                        TagRegistry.Blocks.GEODES_CANNOT_REPLACE,
                        TagRegistry.Blocks.GEODE_INVALID_BLOCKS),
                        new GeodeLayerSettings(1.7D, 2.2D, 3.2D, 4.2D),
                        new GeodeCrackSettings(0.95D, 2.0D, 2),
                        0.35D,
                        0.083D,
                        true,
                        UniformInt.of(4, 6),
                        UniformInt.of(3, 4),
                        UniformInt.of(1, 2),
                        -16,
                        16,
                        0.05D,
                        1));
        register(context,
                GLOWSTONE_GEODE,
                FeatureRegistry.GEODE.value(),
                new GeodeConfiguration(new GeodeBlockSettings(simple(Blocks.AIR),
                        simple(Blocks.NETHERRACK),
                        simple(BUDDING_GLOWSTONE.value()),
                        simple(Blocks.NETHERRACK),
                        simple(Blocks.NETHERRACK),
                        List.of(SMALL_GLOWSTONE_BUD.value().defaultBlockState(),
                                MEDIUM_GLOWSTONE_BUD.value().defaultBlockState(),
                                LARGE_GLOWSTONE_BUD.value().defaultBlockState(),
                                GLOWSTONE_CLUSTER.value().defaultBlockState()),
                        TagRegistry.Blocks.GEODES_CANNOT_REPLACE,
                        TagRegistry.Blocks.GEODE_INVALID_BLOCKS),
                        new GeodeLayerSettings(1.7D, 2.2D, 3.2D, 4.2D),
                        new GeodeCrackSettings(0.95D, 2.0D, 2),
                        0.35D,
                        0.083D,
                        true,
                        UniformInt.of(4, 6),
                        UniformInt.of(3, 4),
                        UniformInt.of(1, 2),
                        -16,
                        16,
                        0.05D,
                        1));
        register(context,
                BASALT_GLOWSTONE_GEODE,
                FeatureRegistry.GEODE.value(),
                new GeodeConfiguration(new GeodeBlockSettings(simple(Blocks.AIR),
                        simple(Blocks.NETHERRACK),
                        simple(BUDDING_BASALT_GLOWSTONE.value()),
                        simple(Blocks.NETHERRACK),
                        simple(Blocks.NETHERRACK),
                        List.of(SMALL_GLOWSTONE_BUD.value().defaultBlockState(),
                                MEDIUM_GLOWSTONE_BUD.value().defaultBlockState(),
                                LARGE_GLOWSTONE_BUD.value().defaultBlockState(),
                                GLOWSTONE_CLUSTER.value().defaultBlockState()),
                        TagRegistry.Blocks.GEODES_CANNOT_REPLACE,
                        TagRegistry.Blocks.GEODE_INVALID_BLOCKS),
                        new GeodeLayerSettings(1.7D, 2.2D, 3.2D, 4.2D),
                        new GeodeCrackSettings(0.95D, 2.0D, 2),
                        0.35D,
                        0.083D,
                        true,
                        UniformInt.of(4, 6),
                        UniformInt.of(3, 4),
                        UniformInt.of(1, 2),
                        -16,
                        16,
                        0.05D,
                        1));
        register(context,
                BLACKSTONE_GLOWSTONE_GEODE,
                FeatureRegistry.GEODE.value(),
                new GeodeConfiguration(new GeodeBlockSettings(simple(Blocks.AIR),
                        simple(Blocks.NETHERRACK),
                        simple(BUDDING_BLACKSTONE_GLOWSTONE.value()),
                        simple(Blocks.NETHERRACK),
                        simple(Blocks.NETHERRACK),
                        List.of(SMALL_GLOWSTONE_BUD.value().defaultBlockState(),
                                MEDIUM_GLOWSTONE_BUD.value().defaultBlockState(),
                                LARGE_GLOWSTONE_BUD.value().defaultBlockState(),
                                GLOWSTONE_CLUSTER.value().defaultBlockState()),
                        TagRegistry.Blocks.GEODES_CANNOT_REPLACE,
                        TagRegistry.Blocks.GEODE_INVALID_BLOCKS),
                        new GeodeLayerSettings(1.7D, 2.2D, 3.2D, 4.2D),
                        new GeodeCrackSettings(0.95D, 2.0D, 2),
                        0.35D,
                        0.083D,
                        true,
                        UniformInt.of(4, 6),
                        UniformInt.of(3, 4),
                        UniformInt.of(1, 2),
                        -16,
                        16,
                        0.05D,
                        1));
        register(context,
                GOLD_NUGGET_GEODE,
                FeatureRegistry.GEODE.value(),
                new GeodeConfiguration(new GeodeBlockSettings(simple(Blocks.AIR),
                        simple(Blocks.NETHERRACK),
                        simple(BUDDING_GOLD_NUGGET.value()),
                        simple(Blocks.NETHERRACK),
                        simple(Blocks.NETHERRACK),
                        List.of(SMALL_GOLD_NUGGET_BUD.value().defaultBlockState(),
                                MEDIUM_GOLD_NUGGET_BUD.value().defaultBlockState(),
                                LARGE_GOLD_NUGGET_BUD.value().defaultBlockState(),
                                GOLD_NUGGET_CLUSTER.value().defaultBlockState()),
                        TagRegistry.Blocks.GEODES_CANNOT_REPLACE,
                        TagRegistry.Blocks.GEODE_INVALID_BLOCKS),
                        new GeodeLayerSettings(1.7D, 2.2D, 3.2D, 4.2D),
                        new GeodeCrackSettings(0.95D, 2.0D, 2),
                        0.35D,
                        0.083D,
                        true,
                        UniformInt.of(4, 6),
                        UniformInt.of(3, 4),
                        UniformInt.of(1, 2),
                        -16,
                        16,
                        0.05D,
                        1));
        register(context,
                BASALT_GOLD_NUGGET_GEODE,
                FeatureRegistry.GEODE.value(),
                new GeodeConfiguration(new GeodeBlockSettings(simple(Blocks.AIR),
                        simple(Blocks.NETHERRACK),
                        simple(BUDDING_BASALT_GOLD_NUGGET.value()),
                        simple(Blocks.NETHERRACK),
                        simple(Blocks.NETHERRACK),
                        List.of(SMALL_GOLD_NUGGET_BUD.value().defaultBlockState(),
                                MEDIUM_GOLD_NUGGET_BUD.value().defaultBlockState(),
                                LARGE_GOLD_NUGGET_BUD.value().defaultBlockState(),
                                GOLD_NUGGET_CLUSTER.value().defaultBlockState()),
                        TagRegistry.Blocks.GEODES_CANNOT_REPLACE,
                        TagRegistry.Blocks.GEODE_INVALID_BLOCKS),
                        new GeodeLayerSettings(1.7D, 2.2D, 3.2D, 4.2D),
                        new GeodeCrackSettings(0.95D, 2.0D, 2),
                        0.35D,
                        0.083D,
                        true,
                        UniformInt.of(4, 6),
                        UniformInt.of(3, 4),
                        UniformInt.of(1, 2),
                        -16,
                        16,
                        0.05D,
                        1));
        register(context,
                BLACKSTONE_GOLD_NUGGET_GEODE,
                FeatureRegistry.GEODE.value(),
                new GeodeConfiguration(new GeodeBlockSettings(simple(Blocks.AIR),
                        simple(Blocks.NETHERRACK),
                        simple(BUDDING_BLACKSTONE_GOLD_NUGGET.value()),
                        simple(Blocks.NETHERRACK),
                        simple(Blocks.NETHERRACK),
                        List.of(SMALL_GOLD_NUGGET_BUD.value().defaultBlockState(),
                                MEDIUM_GOLD_NUGGET_BUD.value().defaultBlockState(),
                                LARGE_GOLD_NUGGET_BUD.value().defaultBlockState(),
                                GOLD_NUGGET_CLUSTER.value().defaultBlockState()),
                        TagRegistry.Blocks.GEODES_CANNOT_REPLACE,
                        TagRegistry.Blocks.GEODE_INVALID_BLOCKS),
                        new GeodeLayerSettings(1.7D, 2.2D, 3.2D, 4.2D),
                        new GeodeCrackSettings(0.95D, 2.0D, 2),
                        0.35D,
                        0.083D,
                        true,
                        UniformInt.of(4, 6),
                        UniformInt.of(3, 4),
                        UniformInt.of(1, 2),
                        -16,
                        16,
                        0.05D,
                        1));
        register(context,
                QUARTZ_GEODE,
                FeatureRegistry.GEODE.value(),
                new GeodeConfiguration(new GeodeBlockSettings(simple(Blocks.AIR),
                        simple(Blocks.NETHERRACK),
                        simple(BUDDING_NETHER_QUARTZ.value()),
                        simple(Blocks.NETHERRACK),
                        simple(Blocks.NETHERRACK),
                        List.of(SMALL_NETHER_QUARTZ_BUD.value().defaultBlockState(),
                                MEDIUM_NETHER_QUARTZ_BUD.value().defaultBlockState(),
                                LARGE_NETHER_QUARTZ_BUD.value().defaultBlockState(),
                                NETHER_QUARTZ_CRYSTAL.value().defaultBlockState()),
                        TagRegistry.Blocks.GEODES_CANNOT_REPLACE,
                        TagRegistry.Blocks.GEODE_INVALID_BLOCKS),
                        new GeodeLayerSettings(1.7D, 2.2D, 3.2D, 4.2D),
                        new GeodeCrackSettings(0.95D, 2.0D, 2),
                        0.35D,
                        0.083D,
                        true,
                        UniformInt.of(4, 6),
                        UniformInt.of(3, 4),
                        UniformInt.of(1, 2),
                        -16,
                        16,
                        0.05D,
                        1));
        register(context,
                BASALT_QUARTZ_GEODE,
                FeatureRegistry.GEODE.value(),
                new GeodeConfiguration(new GeodeBlockSettings(simple(Blocks.AIR),
                        simple(Blocks.NETHERRACK),
                        simple(BUDDING_BASALT_NETHER_QUARTZ.value()),
                        simple(Blocks.NETHERRACK),
                        simple(Blocks.NETHERRACK),
                        List.of(SMALL_NETHER_QUARTZ_BUD.value().defaultBlockState(),
                                MEDIUM_NETHER_QUARTZ_BUD.value().defaultBlockState(),
                                LARGE_NETHER_QUARTZ_BUD.value().defaultBlockState(),
                                NETHER_QUARTZ_CRYSTAL.value().defaultBlockState()),
                        TagRegistry.Blocks.GEODES_CANNOT_REPLACE,
                        TagRegistry.Blocks.GEODE_INVALID_BLOCKS),
                        new GeodeLayerSettings(1.7D, 2.2D, 3.2D, 4.2D),
                        new GeodeCrackSettings(0.95D, 2.0D, 2),
                        0.35D,
                        0.083D,
                        true,
                        UniformInt.of(4, 6),
                        UniformInt.of(3, 4),
                        UniformInt.of(1, 2),
                        -16,
                        16,
                        0.05D,
                        1));
        register(context,
                BLACKSTONE_QUARTZ_GEODE,
                FeatureRegistry.GEODE.value(),
                new GeodeConfiguration(new GeodeBlockSettings(simple(Blocks.AIR),
                        simple(Blocks.NETHERRACK),
                        simple(BUDDING_BLACKSTONE_NETHER_QUARTZ.value()),
                        simple(Blocks.NETHERRACK),
                        simple(Blocks.NETHERRACK),
                        List.of(SMALL_NETHER_QUARTZ_BUD.value().defaultBlockState(),
                                MEDIUM_NETHER_QUARTZ_BUD.value().defaultBlockState(),
                                LARGE_NETHER_QUARTZ_BUD.value().defaultBlockState(),
                                NETHER_QUARTZ_CRYSTAL.value().defaultBlockState()),
                        TagRegistry.Blocks.GEODES_CANNOT_REPLACE,
                        TagRegistry.Blocks.GEODE_INVALID_BLOCKS),
                        new GeodeLayerSettings(1.7D, 2.2D, 3.2D, 4.2D),
                        new GeodeCrackSettings(0.95D, 2.0D, 2),
                        0.35D,
                        0.083D,
                        true,
                        UniformInt.of(4, 6),
                        UniformInt.of(3, 4),
                        UniformInt.of(1, 2),
                        -16,
                        16,
                        0.05D,
                        1));
        register(context,
                ECHO_GEODE,
                FeatureRegistry.GEODE.value(),
                new GeodeConfiguration(new GeodeBlockSettings(simple(Blocks.AIR),
                        simple(Blocks.SCULK),
                        simple(BUDDING_ECHO.value()),
                        simple(Blocks.SCULK),
                        simple(Blocks.SCULK),
                        List.of(SMALL_ECHO_BUD.value().defaultBlockState(),
                                MEDIUM_ECHO_BUD.value().defaultBlockState(),
                                LARGE_ECHO_BUD.value().defaultBlockState(),
                                ECHO_CRYSTAL.value().defaultBlockState()),
                        TagRegistry.Blocks.GEODES_CANNOT_REPLACE,
                        TagRegistry.Blocks.GEODE_INVALID_BLOCKS),
                        new GeodeLayerSettings(1.7D, 2.2D, 3.2D, 4.2D),
                        new GeodeCrackSettings(0.95D, 2.0D, 2),
                        0.35D,
                        0.083D,
                        true,
                        UniformInt.of(4, 6),
                        UniformInt.of(3, 4),
                        UniformInt.of(1, 2),
                        -16,
                        16,
                        0.05D,
                        1));
        register(context,
                WRAPPIST_GEODE,
                FeatureRegistry.GEODE.value(),
                new GeodeConfiguration(new GeodeBlockSettings(simple(Blocks.AIR),
                        simple(WRAPPIST_BLOCK.value()),
                        simple(BUDDING_WRAPPIST.value()),
                        simple(GALCITE.value()),
                        simple(SMOOTH_END_STONE.value()),
                        List.of(SMALL_WRAPPIST_BUD.value().defaultBlockState(),
                                MEDIUM_WRAPPIST_BUD.value().defaultBlockState(),
                                LARGE_WRAPPIST_BUD.value().defaultBlockState(),
                                WRAPPIST_CLUSTER.value().defaultBlockState()),
                        TagRegistry.Blocks.GEODES_CANNOT_REPLACE,
                        TagRegistry.Blocks.GEODE_INVALID_BLOCKS),
                        new GeodeLayerSettings(1.7D, 2.2D, 3.2D, 4.2D),
                        new GeodeCrackSettings(0.95D, 2.0D, 2),
                        0.35D,
                        0.083D,
                        true,
                        UniformInt.of(4, 6),
                        UniformInt.of(3, 4),
                        UniformInt.of(1, 2),
                        -16,
                        16,
                        0.05D,
                        1));
        register(context,
                PRISMARINE_GEODE,
                FeatureRegistry.OCEAN_GEODE.value(),
                new GeodeConfiguration(new GeodeBlockSettings(simple(Blocks.WATER),
                        simple(Blocks.PRISMARINE),
                        simple(BUDDING_PRISMARINE.value()),
                        simple(Blocks.PRISMARINE),
                        simple(Blocks.PRISMARINE),
                        List.of(SMALL_PRISMARINE_BUD.value().defaultBlockState(),
                                MEDIUM_PRISMARINE_BUD.value().defaultBlockState(),
                                LARGE_PRISMARINE_BUD.value().defaultBlockState(),
                                PRISMARINE_CLUSTER.value().defaultBlockState()),
                        TagRegistry.Blocks.GEODES_CANNOT_REPLACE,
                        TagRegistry.Blocks.GEODE_INVALID_BLOCKS),
                        new GeodeLayerSettings(1.7D, 2.2D, 3.2D, 4.2D),
                        new GeodeCrackSettings(0.95D, 2.0D, 2),
                        0.35D,
                        0.083D,
                        true,
                        UniformInt.of(4, 6),
                        UniformInt.of(3, 4),
                        UniformInt.of(1, 2),
                        -16,
                        16,
                        0.05D,
                        1));
        register(context,
                DIAMOND_GEODE,
                FeatureRegistry.GEODE.value(),
                new GeodeConfiguration(new GeodeBlockSettings(simple(Blocks.AIR),
                        simple(Blocks.STONE),
                        simple(BUDDING_DIAMOND.value()),
                        simple(Blocks.STONE),
                        simple(Blocks.STONE),
                        List.of(SMALL_DIAMOND_BUD.value().defaultBlockState(),
                                MEDIUM_DIAMOND_BUD.value().defaultBlockState(),
                                LARGE_DIAMOND_BUD.value().defaultBlockState(),
                                DIAMOND_CRYSTAL.value().defaultBlockState()),
                        TagRegistry.Blocks.GEODES_CANNOT_REPLACE,
                        TagRegistry.Blocks.GEODE_INVALID_BLOCKS),
                        new GeodeLayerSettings(1.7D, 2.2D, 3.2D, 4.2D),
                        new GeodeCrackSettings(0.95D, 2.0D, 2),
                        0.35D,
                        0.083D,
                        true,
                        UniformInt.of(4, 6),
                        UniformInt.of(3, 4),
                        UniformInt.of(1, 2),
                        -16,
                        16,
                        0.05D,
                        1));
        register(context,
                DEEPSLATE_DIAMOND_GEODE,
                FeatureRegistry.GEODE.value(),
                new GeodeConfiguration(new GeodeBlockSettings(simple(Blocks.AIR),
                        simple(Blocks.DEEPSLATE),
                        simple(BUDDING_DEEPSLATE_DIAMOND.value()),
                        simple(Blocks.DEEPSLATE),
                        simple(Blocks.DEEPSLATE),
                        List.of(SMALL_DIAMOND_BUD.value().defaultBlockState(),
                                MEDIUM_DIAMOND_BUD.value().defaultBlockState(),
                                LARGE_DIAMOND_BUD.value().defaultBlockState(),
                                DIAMOND_CRYSTAL.value().defaultBlockState()),
                        TagRegistry.Blocks.GEODES_CANNOT_REPLACE,
                        TagRegistry.Blocks.GEODE_INVALID_BLOCKS),
                        new GeodeLayerSettings(1.7D, 2.2D, 3.2D, 4.2D),
                        new GeodeCrackSettings(0.95D, 2.0D, 2),
                        0.35D,
                        0.083D,
                        true,
                        UniformInt.of(4, 6),
                        UniformInt.of(3, 4),
                        UniformInt.of(1, 2),
                        -16,
                        16,
                        0.05D,
                        1));
        register(context,
                SCULK_DIAMOND_GEODE,
                FeatureRegistry.GEODE.value(),
                new GeodeConfiguration(new GeodeBlockSettings(simple(Blocks.AIR),
                        simple(Blocks.SCULK),
                        simple(BUDDING_SCULK_DIAMOND.value()),
                        simple(Blocks.SCULK),
                        simple(Blocks.SCULK),
                        List.of(SMALL_DIAMOND_BUD.value().defaultBlockState(),
                                MEDIUM_DIAMOND_BUD.value().defaultBlockState(),
                                LARGE_DIAMOND_BUD.value().defaultBlockState(),
                                DIAMOND_CRYSTAL.value().defaultBlockState()),
                        TagRegistry.Blocks.GEODES_CANNOT_REPLACE,
                        TagRegistry.Blocks.GEODE_INVALID_BLOCKS),
                        new GeodeLayerSettings(1.7D, 2.2D, 3.2D, 4.2D),
                        new GeodeCrackSettings(0.95D, 2.0D, 2),
                        0.35D,
                        0.083D,
                        true,
                        UniformInt.of(4, 6),
                        UniformInt.of(3, 4),
                        UniformInt.of(1, 2),
                        -16,
                        16,
                        0.05D,
                        1));
        register(context,
                EMERALD_GEODE,
                FeatureRegistry.GEODE.value(),
                new GeodeConfiguration(new GeodeBlockSettings(simple(Blocks.AIR),
                        simple(Blocks.STONE),
                        simple(BUDDING_EMERALD.value()),
                        simple(Blocks.STONE),
                        simple(Blocks.STONE),
                        List.of(SMALL_EMERALD_BUD.value().defaultBlockState(),
                                MEDIUM_EMERALD_BUD.value().defaultBlockState(),
                                LARGE_EMERALD_BUD.value().defaultBlockState(),
                                EMERALD_CLUSTER.value().defaultBlockState()),
                        TagRegistry.Blocks.GEODES_CANNOT_REPLACE,
                        TagRegistry.Blocks.GEODE_INVALID_BLOCKS),
                        new GeodeLayerSettings(1.7D, 2.2D, 3.2D, 4.2D),
                        new GeodeCrackSettings(0.95D, 2.0D, 2),
                        0.35D,
                        0.083D,
                        true,
                        UniformInt.of(4, 6),
                        UniformInt.of(3, 4),
                        UniformInt.of(1, 2),
                        -16,
                        16,
                        0.05D,
                        1));
        register(context,
                DEEPSLATE_EMERALD_GEODE,
                FeatureRegistry.GEODE.value(),
                new GeodeConfiguration(new GeodeBlockSettings(simple(Blocks.AIR),
                        simple(Blocks.DEEPSLATE),
                        simple(BUDDING_DEEPSLATE_EMERALD.value()),
                        simple(Blocks.DEEPSLATE),
                        simple(Blocks.DEEPSLATE),
                        List.of(SMALL_EMERALD_BUD.value().defaultBlockState(),
                                MEDIUM_EMERALD_BUD.value().defaultBlockState(),
                                LARGE_EMERALD_BUD.value().defaultBlockState(),
                                EMERALD_CLUSTER.value().defaultBlockState()),
                        TagRegistry.Blocks.GEODES_CANNOT_REPLACE,
                        TagRegistry.Blocks.GEODE_INVALID_BLOCKS),
                        new GeodeLayerSettings(1.7D, 2.2D, 3.2D, 4.2D),
                        new GeodeCrackSettings(0.95D, 2.0D, 2),
                        0.35D,
                        0.083D,
                        true,
                        UniformInt.of(4, 6),
                        UniformInt.of(3, 4),
                        UniformInt.of(1, 2),
                        -16,
                        16,
                        0.05D,
                        1));
        register(context,
                SCULK_EMERALD_GEODE,
                FeatureRegistry.GEODE.value(),
                new GeodeConfiguration(new GeodeBlockSettings(simple(Blocks.AIR),
                        simple(Blocks.SCULK),
                        simple(BUDDING_SCULK_EMERALD.value()),
                        simple(Blocks.SCULK),
                        simple(Blocks.SCULK),
                        List.of(SMALL_EMERALD_BUD.value().defaultBlockState(),
                                MEDIUM_EMERALD_BUD.value().defaultBlockState(),
                                LARGE_EMERALD_BUD.value().defaultBlockState(),
                                EMERALD_CLUSTER.value().defaultBlockState()),
                        TagRegistry.Blocks.GEODES_CANNOT_REPLACE,
                        TagRegistry.Blocks.GEODE_INVALID_BLOCKS),
                        new GeodeLayerSettings(1.7D, 2.2D, 3.2D, 4.2D),
                        new GeodeCrackSettings(0.95D, 2.0D, 2),
                        0.35D,
                        0.083D,
                        true,
                        UniformInt.of(4, 6),
                        UniformInt.of(3, 4),
                        UniformInt.of(1, 2),
                        -16,
                        16,
                        0.05D,
                        1));
        register(context,
                LAPIS_GEODE,
                FeatureRegistry.GEODE.value(),
                new GeodeConfiguration(new GeodeBlockSettings(simple(Blocks.AIR),
                        simple(Blocks.STONE),
                        simple(BUDDING_LAPIS.value()),
                        simple(Blocks.STONE),
                        simple(Blocks.STONE),
                        List.of(SMALL_LAPIS_BUD.value().defaultBlockState(),
                                MEDIUM_LAPIS_BUD.value().defaultBlockState(),
                                LARGE_LAPIS_BUD.value().defaultBlockState(),
                                LAPIS_CLUSTER.value().defaultBlockState()),
                        TagRegistry.Blocks.GEODES_CANNOT_REPLACE,
                        TagRegistry.Blocks.GEODE_INVALID_BLOCKS),
                        new GeodeLayerSettings(1.7D, 2.2D, 3.2D, 4.2D),
                        new GeodeCrackSettings(0.95D, 2.0D, 2),
                        0.35D,
                        0.083D,
                        true,
                        UniformInt.of(4, 6),
                        UniformInt.of(3, 4),
                        UniformInt.of(1, 2),
                        -16,
                        16,
                        0.05D,
                        1));
        register(context,
                DEEPSLATE_LAPIS_GEODE,
                FeatureRegistry.GEODE.value(),
                new GeodeConfiguration(new GeodeBlockSettings(simple(Blocks.AIR),
                        simple(Blocks.DEEPSLATE),
                        simple(BUDDING_DEEPSLATE_LAPIS.value()),
                        simple(Blocks.DEEPSLATE),
                        simple(Blocks.DEEPSLATE),
                        List.of(SMALL_LAPIS_BUD.value().defaultBlockState(),
                                MEDIUM_LAPIS_BUD.value().defaultBlockState(),
                                LARGE_LAPIS_BUD.value().defaultBlockState(),
                                LAPIS_CLUSTER.value().defaultBlockState()),
                        TagRegistry.Blocks.GEODES_CANNOT_REPLACE,
                        TagRegistry.Blocks.GEODE_INVALID_BLOCKS),
                        new GeodeLayerSettings(1.7D, 2.2D, 3.2D, 4.2D),
                        new GeodeCrackSettings(0.95D, 2.0D, 2),
                        0.35D,
                        0.083D,
                        true,
                        UniformInt.of(4, 6),
                        UniformInt.of(3, 4),
                        UniformInt.of(1, 2),
                        -16,
                        16,
                        0.05D,
                        1));
        register(context,
                SCULK_LAPIS_GEODE,
                FeatureRegistry.GEODE.value(),
                new GeodeConfiguration(new GeodeBlockSettings(simple(Blocks.AIR),
                        simple(Blocks.SCULK),
                        simple(BUDDING_SCULK_LAPIS.value()),
                        simple(Blocks.SCULK),
                        simple(Blocks.SCULK),
                        List.of(SMALL_LAPIS_BUD.value().defaultBlockState(),
                                MEDIUM_LAPIS_BUD.value().defaultBlockState(),
                                LARGE_LAPIS_BUD.value().defaultBlockState(),
                                LAPIS_CLUSTER.value().defaultBlockState()),
                        TagRegistry.Blocks.GEODES_CANNOT_REPLACE,
                        TagRegistry.Blocks.GEODE_INVALID_BLOCKS),
                        new GeodeLayerSettings(1.7D, 2.2D, 3.2D, 4.2D),
                        new GeodeCrackSettings(0.95D, 2.0D, 2),
                        0.35D,
                        0.083D,
                        true,
                        UniformInt.of(4, 6),
                        UniformInt.of(3, 4),
                        UniformInt.of(1, 2),
                        -16,
                        16,
                        0.05D,
                        1));
        register(context,
                REDSTONE_GEODE,
                FeatureRegistry.GEODE.value(),
                new GeodeConfiguration(new GeodeBlockSettings(simple(Blocks.AIR),
                        simple(Blocks.STONE),
                        simple(BUDDING_REDSTONE.value()),
                        simple(Blocks.STONE),
                        simple(Blocks.STONE),
                        List.of(SMALL_REDSTONE_BUD.value().defaultBlockState(),
                                MEDIUM_REDSTONE_BUD.value().defaultBlockState(),
                                LARGE_REDSTONE_BUD.value().defaultBlockState(),
                                REDSTONE_CRYSTAL.value().defaultBlockState()),
                        TagRegistry.Blocks.GEODES_CANNOT_REPLACE,
                        TagRegistry.Blocks.GEODE_INVALID_BLOCKS),
                        new GeodeLayerSettings(1.7D, 2.2D, 3.2D, 4.2D),
                        new GeodeCrackSettings(0.95D, 2.0D, 2),
                        0.35D,
                        0.083D,
                        true,
                        UniformInt.of(4, 6),
                        UniformInt.of(3, 4),
                        UniformInt.of(1, 2),
                        -16,
                        16,
                        0.05D,
                        1));
        register(context,
                DEEPSLATE_REDSTONE_GEODE,
                FeatureRegistry.GEODE.value(),
                new GeodeConfiguration(new GeodeBlockSettings(simple(Blocks.AIR),
                        simple(Blocks.DEEPSLATE),
                        simple(BUDDING_DEEPSLATE_REDSTONE.value()),
                        simple(Blocks.DEEPSLATE),
                        simple(Blocks.DEEPSLATE),
                        List.of(SMALL_REDSTONE_BUD.value().defaultBlockState(),
                                MEDIUM_REDSTONE_BUD.value().defaultBlockState(),
                                LARGE_REDSTONE_BUD.value().defaultBlockState(),
                                REDSTONE_CRYSTAL.value().defaultBlockState()),
                        TagRegistry.Blocks.GEODES_CANNOT_REPLACE,
                        TagRegistry.Blocks.GEODE_INVALID_BLOCKS),
                        new GeodeLayerSettings(1.7D, 2.2D, 3.2D, 4.2D),
                        new GeodeCrackSettings(0.95D, 2.0D, 2),
                        0.35D,
                        0.083D,
                        true,
                        UniformInt.of(4, 6),
                        UniformInt.of(3, 4),
                        UniformInt.of(1, 2),
                        -16,
                        16,
                        0.05D,
                        1));
        register(context,
                SCULK_REDSTONE_GEODE,
                FeatureRegistry.GEODE.value(),
                new GeodeConfiguration(new GeodeBlockSettings(simple(Blocks.AIR),
                        simple(Blocks.SCULK),
                        simple(BUDDING_SCULK_REDSTONE.value()),
                        simple(Blocks.SCULK),
                        simple(Blocks.SCULK),
                        List.of(SMALL_REDSTONE_BUD.value().defaultBlockState(),
                                MEDIUM_REDSTONE_BUD.value().defaultBlockState(),
                                LARGE_REDSTONE_BUD.value().defaultBlockState(),
                                REDSTONE_CRYSTAL.value().defaultBlockState()),
                        TagRegistry.Blocks.GEODES_CANNOT_REPLACE,
                        TagRegistry.Blocks.GEODE_INVALID_BLOCKS),
                        new GeodeLayerSettings(1.7D, 2.2D, 3.2D, 4.2D),
                        new GeodeCrackSettings(0.95D, 2.0D, 2),
                        0.35D,
                        0.083D,
                        true,
                        UniformInt.of(4, 6),
                        UniformInt.of(3, 4),
                        UniformInt.of(1, 2),
                        -16,
                        16,
                        0.05D,
                        1));
        register(context,
                CELESTITE_GEODE,
                FeatureRegistry.GEODE.value(),
                new GeodeConfiguration(new GeodeBlockSettings(simple(Blocks.AIR),
                        simple(CELESTITE_BLOCK.value()),
                        simple(BUDDING_CELESTITE.value()),
                        simple(Blocks.CALCITE),
                        simple(Blocks.MUD),
                        List.of(SMALL_CELESTITE_BUD.value().defaultBlockState(),
                                MEDIUM_CELESTITE_BUD.value().defaultBlockState(),
                                LARGE_CELESTITE_BUD.value().defaultBlockState(),
                                CELESTITE_CLUSTER.value().defaultBlockState()),
                        TagRegistry.Blocks.GEODES_CANNOT_REPLACE,
                        TagRegistry.Blocks.GEODE_INVALID_BLOCKS),
                        new GeodeLayerSettings(1.7D, 2.2D, 3.2D, 4.2D),
                        new GeodeCrackSettings(0.95D, 2.0D, 2),
                        0.35D,
                        0.083D,
                        true,
                        UniformInt.of(4, 6),
                        UniformInt.of(3, 4),
                        UniformInt.of(1, 2),
                        -16,
                        16,
                        0.05D,
                        1));
        register(context,
                PINK_TOPAZ_GEODE,
                FeatureRegistry.GEODE.value(),
                new GeodeConfiguration(new GeodeBlockSettings(simple(Blocks.AIR),
                        simple(PINK_TOPAZ_BLOCK.value()),
                        simple(BUDDING_PINK_TOPAZ.value()),
                        simple(Blocks.CALCITE),
                        simple(Blocks.TUFF),
                        List.of(SMALL_PINK_TOPAZ_BUD.value().defaultBlockState(),
                                MEDIUM_PINK_TOPAZ_BUD.value().defaultBlockState(),
                                LARGE_PINK_TOPAZ_BUD.value().defaultBlockState(),
                                PINK_TOPAZ_CRYSTAL.value().defaultBlockState()),
                        TagRegistry.Blocks.GEODES_CANNOT_REPLACE,
                        TagRegistry.Blocks.GEODE_INVALID_BLOCKS),
                        new GeodeLayerSettings(1.7D, 2.2D, 3.2D, 4.2D),
                        new GeodeCrackSettings(0.95D, 2.0D, 2),
                        0.35D,
                        0.083D,
                        true,
                        UniformInt.of(4, 6),
                        UniformInt.of(3, 4),
                        UniformInt.of(1, 2),
                        -16,
                        16,
                        0.05D,
                        1));

    }

    public static ResourceKey<ConfiguredFeature<?, ?>> registerKey(String name) {
        return ModRegistry.REGISTRY.makeResourceKey(Registries.CONFIGURED_FEATURE, name);
    }

    private static <FC extends FeatureConfiguration, F extends Feature<FC>> void register(BootstrapContext<ConfiguredFeature<?, ?>> context, ResourceKey<ConfiguredFeature<?, ?>> key, F feature, FC configuration) {
        context.register(key, new ConfiguredFeature<>(feature, configuration));
    }

    public static void bootstrap() {
        // NO-OP
    }
}
